<a href="https://colab.research.google.com/github/HisakaKoji/bert-japanese/blob/master/numpytest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p><img alt="Colaboratory logo" height="45px" src="https://colab.research.google.com/img/colab_favicon.ico" align="left" hspace="10px" vspace="0px"></p>

<h1>Colaboratory へようこそ</h1>


Colaboratory は、完全にクラウドで実行される Jupyter ノートブック環境です。設定不要で、無料でご利用になれます。

Colaboratory を使用すると、コードの記述と実行、解析の保存や共有、強力なコンピューティング リソースへのアクセスなどをブラウザからすべて無料で行えます。

In [3]:
import json
import numpy as np

data1 = np.ndarray([])
i = 0
with open('output.txt') as fin:
    for i,line in enumerate(fin):
        data = json.loads(line)
        value = data['features'][0]['layers'][0]['values']
        value = value/np.linalg.norm(value)
        if i == 0:
          data1 = value
        else:
          data1 = np.vstack((data1, value ) )
          
        if (i + 1 )% 1000 == 0:
          print(value[0])

 

0.014171119270801722
0.005800054664400617
0.044185541400192145
0.06742286188265184
0.019006847661925647
0.0438154435098609
0.010119518200853123
0.004365301355075212
0.0156403062343755
0.03644361103882034
0.017667976891186567
-0.0259967507410785
0.025423051952224992
0.01716848759033307
0.028227958415249232
-0.0015463641046876123
0.04546685077384249
0.04329154156220334
0.027751727381377624
0.05335159078340094
0.019446352590464545
0.026979546068716293
0.01325555648652983
0.013485765660977755


In [0]:
import numpy as np
a = np.loadtxt('hisaka1.txt')

In [0]:
a1 = a[:15000]
a2 = a[15000:]

In [0]:
b1 = np.dot(a1,a1.T)

In [0]:
b2 = np.dot(a1,a2.T)

In [0]:
b3 = np.dot(a2,a1.T)

In [0]:
b4 = np.dot(a2,a2.T)

In [0]:
np.savetxt('b1.txt',b1)

In [0]:
np.savetxt('b2.txt',b2)

In [0]:
np.savetxt('b3.txt',b3)

In [0]:
np.savetxt('b4.txt',b4)

In [13]:
b

array([[1.        , 0.66253111, 0.77468838, ..., 0.82324855, 0.87658687,
        0.81912808],
       [0.66253111, 1.        , 0.72381507, ..., 0.67041444, 0.63106298,
        0.69772067],
       [0.77468838, 0.72381507, 1.        , ..., 0.77819966, 0.7583569 ,
        0.82779748],
       ...,
       [0.82324855, 0.67041444, 0.77819966, ..., 1.        , 0.84078287,
        0.86188496],
       [0.87658687, 0.63106298, 0.7583569 , ..., 0.84078287, 1.        ,
        0.81822517],
       [0.81912808, 0.69772067, 0.82779748, ..., 0.86188496, 0.81822517,
        1.        ]])

In [0]:
np.savetxt('hisaka1.txt',data1)

In [0]:
c = np.dot(data1,data1.T)


In [0]:
np.savetxt('hisaka.txt',c)

In [38]:
c

array([[1.        , 0.66253111, 0.77468838, ..., 0.90355356, 0.84764607,
        0.83430607],
       [0.66253111, 1.        , 0.72381507, ..., 0.72273542, 0.7318715 ,
        0.69949401],
       [0.77468838, 0.72381507, 1.        , ..., 0.80718624, 0.73698685,
        0.84746014],
       ...,
       [0.90355356, 0.72273542, 0.80718624, ..., 1.        , 0.87804896,
        0.89486417],
       [0.84764607, 0.7318715 , 0.73698685, ..., 0.87804896, 1.        ,
        0.83137427],
       [0.83430607, 0.69949401, 0.84746014, ..., 0.89486417, 0.83137427,
        1.        ]])

In [0]:
print( np.where(c> 0.92) )

In [0]:
from google.colab import drive
drive.mount('/content/drive')

In [43]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[10,20,30],[40,50,60],[70,80,90]])
c = np.vstack((a,b))
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [0]:
c = np.vstack((c,b))

In [45]:
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 20, 30],
       [40, 50, 60],
       [70, 80, 90],
       [10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [23]:
type(data['features'][0]['layers'][0]['values'])

list

In [0]:
#@title Colaboratory の概要 { display-mode: "form" }
#@markdown この 3 分間の動画では、Colaboratory の主な機能の概要をご紹介します。
from IPython.display import YouTubeVideo
YouTubeVideo('inN8seMm7UI', width=600, height=400)

## はじめに

ご覧になっているドキュメントは、Colaboratory でホストされている <a href="https://jupyter.org/">Jupyter ノートブック</a>です。静的なページではなく、Python やその他の言語でコードを記述して実行できるインタラクティブな環境です。

たとえば次の<strong>コードセル</strong>には、値を計算して変数に保存し、結果を出力する短い Python スクリプトが含まれています。

In [0]:
seconds_in_a_day = 24 * 60 * 60
seconds_in_a_day

86400

上記のセルのコードを実行するには、セルをクリックして選択し、コードの左側にある再生ボタンをクリックするか、キーボード ショートカット「command+return」または「Ctrl+Enter」を使用します。

すべてのセルで同じグローバル状態が変更されるため、セルの実行によって定義した変数を、他のセルで使用することができます。

In [0]:
seconds_in_a_week = 7 * seconds_in_a_day
seconds_in_a_week

604800

Colaboratory ノートブックの操作について詳しくは、<a href="/notebooks/basic_features_overview.ipynb">Colaboratory の概要</a>をご覧ください。


## その他のリソース

Python、Jupyter、Colaboratory、および関連するツールを最大限に活用する方法については、以下のリソースをご覧ください。

### Colaboratory でのノートブックの操作
- [Colaboratory の概要](/notebooks/basic_features_overview.ipynb)
- [markdown のガイド](/notebooks/markdown_guide.ipynb)
- [ライブラリのインポートと依存関係のインストール](/notebooks/snippets/importing_libraries.ipynb)
- [GitHub でのノートブックの保存と読み込み](https://colab.research.google.com/github/googlecolab/colabtools/blob/master/notebooks/colab-github-demo.ipynb)
- [インタラクティブなフォーム](/notebooks/forms.ipynb)
- [インタラクティブなウィジェット](/notebooks/widgets.ipynb)

### データの操作
- [データの読み込み: ドライブ、スプレッドシート、Google Cloud Storage](/notebooks/io.ipynb) 
- [グラフ: データの視覚化](/notebooks/charts.ipynb)
- [BigQuery を使ってみる](/notebooks/bigquery.ipynb)

### 機械学習の集中講座
Google の機械学習に関するオンライン コースからいくつかのノートブックをご紹介します。詳しくは、<a href="https://developers.google.com/machine-learning/crash-course/">全コースのウェブサイト</a>をご覧ください。
- [pandas の概要](/notebooks/mlcc/intro_to_pandas.ipynb)
- [Tensorflow のコンセプト](/notebooks/mlcc/tensorflow_programming_concepts.ipynb)
- [TensorFlow での最初の手順](/notebooks/mlcc/first_steps_with_tensor_flow.ipynb)
- [ニューラル ネットの概要](/notebooks/mlcc/intro_to_neural_nets.ipynb)
- [スパースデータと埋め込みの概要](/notebooks/mlcc/intro_to_sparse_data_and_embeddings.ipynb)

### アクセラレータの使用
- [TensorFlow と GPU](/notebooks/gpu.ipynb)
- [TensorFlow と TPU](/notebooks/tpu.ipynb)

## 機械学習の例: Seedbank

Colaboratory で実現されたインタラクティブな機械学習解析のさまざまな例を確認するには、<a href="https://research.google.com/seedbank/">Seedbank</a> プロジェクトをご覧ください。

おすすめの例をご紹介します。

- <a href="https://research.google.com/seedbank/seed/neural_style_transfer_with_tfkeras">ニューラル スタイル転送</a>: ディープ ラーニングを使用して画像間でスタイルを転送します。
- <a href="https://research.google.com/seedbank/seed/ez_nsynth">EZ NSynth</a>: 音声と WaveNet オートエンコーダを合成します。
- <a href="https://research.google.com/seedbank/seed/fashion_mnist_with_keras_and_tpus">Keras と TPU で Fashion MNIST</a>: ファッション関連の画像をディープ ラーニングで分類します。
- <a href="https://research.google.com/seedbank/seed/deepdream">DeepDream</a>: 独自の写真から DeepDream 画像を生成します。
- <a href="https://research.google.com/seedbank/seed/convolutional_vae">畳み込み VAE</a>: 手書きの数字の生成モデルを作成します。